---
galaxy_info:
  role_name: monitoring
  namespace: jengasec
  author: Strathmore Cybersecurity Club
  description: Prometheus, Grafana, and node_exporter.
  company: Strathmore University
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - jengasec
    - infrastructure

dependencies: []
