---
galaxy_info:
  role_name: redis
  namespace: jengasec
  author: Strathmore Cybersecurity Club
  description: Redis cache and session store, hardened and memory-capped.
  company: Strathmore University
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - jengasec
    - infrastructure
    - redis
    - cache

dependencies: []
