---
galaxy_info:
  role_name: loadbalancer
  namespace: jengasec
  author: Strathmore Cybersecurity Club
  description: HAProxy or nginx load balancing across application hosts.
  company: Strathmore University
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - jengasec
    - infrastructure

dependencies: []
