---
galaxy_info:
  role_name: postgresql
  namespace: jengasec
  author: Strathmore Cybersecurity Club
  description: PostgreSQL server, tuning, authentication, databases and roles.
  company: Strathmore University
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - jengasec
    - infrastructure
    - postgresql
    - database

dependencies: []
